[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
custom_token = "9EQj1fWttG6tLmGnyZShJFWpBGmQd1FHFTzjTYHYsGSK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/arlen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
